In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [4]:
# Convert 4th row into lower Case
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

## Convert into Lower case

In [5]:
df['review'] = df['review'].str.lower()

In [6]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Remove HTML Tags

In [7]:
import re
def remove_html_tag(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [8]:
text = "<html><body><p> Book Name </p><p> Author - J.K. Rowling </p><p> Click here to <a href='http://example.com'>download</a></p></body></html>"

In [9]:
remove_html_tag(text)

' Book Name  Author - J.K. Rowling  Click here to download'

In [10]:
df['review'].apply(remove_html_tag)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

## Remove URLs

In [11]:
text1 = 'Check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
text2 = 'Check out my notebook http://www.kaggle.com/campusx/notebook8223fc1abb'
text3 = 'Google search here www.google.com'
text4 = 'For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'

In [12]:
text4

'For notebook click https://www.kaggle.com/campusx/notebook8223fc1abb to search check www.google.com'

In [13]:
def remove_urls(text):
    pattern_url = re.compile(r'https?://\S+|www\.\S+')
    return pattern_url.sub(r'', text)

In [14]:
remove_urls(text4)

'For notebook click  to search check '

## Remove Punctuation

In [15]:
import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [16]:
exclude = string.punctuation

In [17]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char, '')
    return text

In [18]:
text = 'String. With. Punctuation?'

In [19]:
remove_punc(text)

'String With Punctuation'

In [20]:
def remove_punc1(text):
    return text.translate(str.maketrans('','', exclude))

In [21]:
remove_punc1(text)

'String With Punctuation'

In [22]:
df1 = pd.read_csv('twitter-haters-speech.csv')
df1.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [23]:
df1.sample(5)

          id  label                                              tweet
9973    9974      0  bo3 contracts and blackjack on tuesday, iw/cod...
11684  11685      0         this @user will never resolve my issue..
19861  19862      0  .@user out-drawn and out-gunned by fuckin #rin...
7504    7505      0  you hu my feelings so much ð­ð­ you staing...
6529    6530      0  only 43 days until #estuaryfringefestival 2016...

In [24]:
def remove_punctuation(text):
    return text.translate(str.maketrans('','',exclude))

In [25]:
df1['tweet'] = df1['tweet'].apply(remove_punctuation)

In [26]:
df1.sample(3)

          id  label                                              tweet
31567  31568      0  this weekend brings one of our favourite event...
23772  23773      0  we went to the severnvalley park she had a run...
7485    7486      0  tubbytoons xoxoorlando tubbytoons orlando orla...

## Chat Word Treatment

In [27]:
data_dict = {}

with open('slang.txt', 'r') as file:
    for line in file:
        key, value = line.strip().split("=")
        data_dict[key] = value

print(data_dict)

{'A3': 'Anytime, Anywhere, Anyplace', 'ADIH': 'Another Day In Hell', 'AFK': 'Away From Keyboard', 'AFAIK': 'As Far As I Know', 'ASAP': 'As Soon As Possible', 'ASL': 'Age, Sex, Location', 'ATK': 'At The Keyboard', 'ATM': 'At The Moment', 'BAE': 'Before Anyone Else', 'BAK': 'Back At Keyboard', 'BBL': 'Be Back Later', 'BBS': 'Be Back Soon', 'BFN': 'Bye For Now', 'B4N': 'Bye For Now', 'BRB': 'Be Right Back', 'BRUH': 'Bro', 'BRT': 'Be Right There', 'BSAAW': 'Big Smile And A Wink', 'BTW': 'By The Way', 'BWL': 'Bursting With Laughter', 'CSL': 'Can’t Stop Laughing', 'CU': 'See You', 'CUL8R': 'See You Later', 'CYA': 'See You', 'DM': 'Direct Message', 'FAQ': 'Frequently Asked Questions', 'FC': 'Fingers Crossed', 'FIMH': 'Forever In My Heart', 'FOMO': 'Fear Of Missing Out', 'FR': 'For Real', 'FWIW': "For What It's Worth", 'FYP': 'For You Page', 'FYI': 'For Your Information', 'G9': 'Genius', 'GAL': 'Get A Life', 'GG': 'Good Game', 'GMTA': 'Great Minds Think Alike', 'GN': 'Good Night', 'GOAT': 'Greatest Of All Time', 'GR8': 'Great!', 'HBD': 'Happy Birthday', 'IC': 'I See', 'ICQ': 'I Seek You', 'IDC': 'I Don’t Care', 'IDK': "I Don't Know", 'IFYP': 'I Feel Your Pain', 'ILU': 'I Love You', 'ILY': 'I Love You', 'IMHO': 'In My Honest/Humble Opinion', 'IMU': 'I Miss You', 'IMO': 'In My Opinion', 'IOW': 'In Other Words', 'IRL': 'In Real Life', 'IYKYK': 'If You Know, You Know', 'JK': 'Just Kidding', 'KISS': 'Keep It Simple, Stupid', 'L': 'Loss', 'L8R': 'Later', 'LDR': 'Long Distance Relationship', 'LMK': 'Let Me Know', 'LMAO': 'Laughing My A** Off', 'LOL': 'Laughing Out Loud', 'LTNS': 'Long Time No See', 'M8': 'Mate', 'MFW': 'My Face When', 'MID': 'Mediocre', 'MRW': 'My Reaction When', 'MTE': 'My Thoughts Exactly', 'NVM': 'Never Mind', 'NRN': 'No Reply Necessary', 'NPC': 'Non-Player Character', 'OIC': 'Oh I See', 'OP': 'Overpowered', 'PITA': 'Pain In The A**', 'POV': 'Point Of View', 'PRT': 'Party', 'PRW': 'Parents Are Watching', 'ROFL': 'Rolling On The Floor Laughing', 'ROFLOL': 'Rolling On The Floor Laughing Out Loud', 'ROTFLMAO': 'Rolling On The Floor Laughing My A** Off', 'RN': 'Right Now', 'SK8': 'Skate', 'STATS': 'Your Sex And Age', 'SUS': 'Suspicious', 'TBH': 'To Be Honest', 'TFW': 'That Feeling When', 'THX': 'Thank You', 'TIME': 'Tears In My Eyes', 'TLDR': 'Too Long, Didn’t Read', 'TNTL': 'Trying Not To Laugh', 'TTFN': 'Ta-Ta For Now!', 'TTYL': 'Talk To You Later', 'U': 'You', 'U2': 'You Too', 'U4E': 'Yours For Ever', 'W': 'Win', 'W8': 'Wait...', 'WB': 'Welcome Back', 'WTF': 'What The F**k', 'WTG': 'Way To Go!', 'WUF': 'Where Are You From?', 'WYD': 'What You Doing?', 'WYWH': 'Wish You Were Here', 'ZZZ': 'Sleeping, Bored, Tired'}

In [28]:
data_dict

{'A3': 'Anytime, Anywhere, Anyplace',
 'ADIH': 'Another Day In Hell',
 'AFK': 'Away From Keyboard',
 'AFAIK': 'As Far As I Know',
 'ASAP': 'As Soon As Possible',
 'ASL': 'Age, Sex, Location',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'BAE': 'Before Anyone Else',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRUH': 'Bro',
 'BRT': 'Be Right There',
 'BSAAW': 'Big Smile And A Wink',
 'BTW': 'By The Way',
 'BWL': 'Bursting With Laughter',
 'CSL': 'Can’t Stop Laughing',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'DM': 'Direct Message',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FIMH': 'Forever In My Heart',
 'FOMO': 'Fear Of Missing Out',
 'FR': 'For Real',
 'FWIW': "For What It's Worth",
 'FYP': 'For You Page',
 'FYI': 'For Your Information',
 'G9': 'Genius',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GMTA': 'Great Minds Think Alike',
 'GN': 'Good Night',
 'GOAT': 'Greatest Of All Time',
 'GR8': 'Great!',
 'HBD': 'Happy Birthday',
 'IC': 'I See',
 'ICQ': 'I Seek You',
 'IDC': 'I Don’t Care',
 'IDK': "I Don't Know",
 'IFYP': 'I Feel Your Pain',
 'ILU': 'I Love You',
 'ILY': 'I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMU': 'I Miss You',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'IYKYK': 'If You Know, You Know',
 'JK': 'Just Kidding',
 'KISS': 'Keep It Simple, Stupid',
 'L': 'Loss',
 'L8R': 'Later',
 'LDR': 'Long Distance Relationship',
 'LMK': 'Let Me Know',
 'LMAO': 'Laughing My A** Off',
 'LOL': 'Laughing Out Loud',
 'LTNS': 'Long Time No See',
 'M8': 'Mate',
 'MFW': 'My Face When',
 'MID': 'Mediocre',
 'MRW': 'My Reaction When',
 'MTE': 'My Thoughts Exactly',
 'NVM': 'Never Mind',
 'NRN': 'No Reply Necessary',
 'NPC': 'Non-Player Character',
 'OIC': 'Oh I See',
 'OP': 'Overpowered',
 'PITA': 'Pain In The A**',
 'POV': 'Point Of View',
 'PRT': 'Party',
 'PRW': 'Parents Are Watching',
 'ROFL': 'Rolling On The Floor Laughing',
 'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
 'ROTFLMAO': 'Rolling On The Floor Laughing My A** Off',
 'RN': 'Right Now',
 'SK8': 'Skate',
 'STATS': 'Your Sex And Age',
 'SUS': 'Suspicious',
 'TBH': 'To Be Honest',
 'TFW': 'That Feeling When',
 'THX': 'Thank You',
 'TIME': 'Tears In My Eyes',
 'TLDR': 'Too Long, Didn’t Read',
 'TNTL': 'Trying Not To Laugh',
 'TTFN': 'Ta-Ta For Now!',
 'TTYL': 'Talk To You Later',
 'U': 'You',
 'U2': 'You Too',
 'U4E': 'Yours For Ever',
 'W': 'Win',
 'W8': 'Wait...',
 'WB': 'Welcome Back',
 'WTF': 'What The F**k',
 'WTG': 'Way To Go!',
 'WUF': 'Where Are You From?',
 'WYD': 'What You Doing?',
 'WYWH': 'Wish You Were Here',
 'ZZZ': 'Sleeping, Bored, Tired'}

In [29]:
def chat_convesion(text):
    new_text = []

    for w in text.split():
        if w.upper() in data_dict:
            new_text.append(data_dict[w.upper()])
        else:
            new_text.append(w)

    return " ".join(new_text)

In [30]:
chat_convesion('ASAP meet me')

'As Soon As Possible meet me'

In [31]:
chat_convesion('AFAIK you are the best!!')

'As Far As I Know you are the best!!'

## Spelling correction

In [32]:
from textblob import TextBlob

In [33]:
incorrect_text = 'ceertain conditionas durind seveal ggenerations aree moodified in the same maner.'

textblob = TextBlob(incorrect_text)

textblob.correct().string

'certain conditions during several generations are modified in the same manner.'

## Remove Stop Words

##### a, an, the, of, are, my, etc..

In [34]:
from nltk.corpus import stopwords

In [35]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [36]:
stopwords.words('spanish')

['de',
 'la',
 'que',
 'el',
 'en',
 'y',
 'a',
 'los',
 'del',
 'se',
 'las',
 'por',
 'un',
 'para',
 'con',
 'no',
 'una',
 'su',
 'al',
 'lo',
 'como',
 'más',
 'pero',
 'sus',
 'le',
 'ya',
 'o',
 'este',
 'sí',
 'porque',
 'esta',
 'entre',
 'cuando',
 'muy',
 'sin',
 'sobre',
 'también',
 'me',
 'hasta',
 'hay',
 'donde',
 'quien',
 'desde',
 'todo',
 'nos',
 'durante',
 'todos',
 'uno',
 'les',
 'ni',
 'contra',
 'otros',
 'ese',
 'eso',
 'ante',
 'ellos',
 'e',
 'esto',
 'mí',
 'antes',
 'algunos',
 'qué',
 'unos',
 'yo',
 'otro',
 'otras',
 'otra',
 'él',
 'tanto',
 'esa',
 'estos',
 'mucho',
 'quienes',
 'nada',
 'muchos',
 'cual',
 'poco',
 'ella',
 'estar',
 'estas',
 'algunas',
 'algo',
 'nosotros',
 'mi',
 'mis',
 'tú',
 'te',
 'ti',
 'tu',
 'tus',
 'ellas',
 'nosotras',
 'vosotros',
 'vosotras',
 'os',
 'mío',
 'mía',
 'míos',
 'mías',
 'tuyo',
 'tuya',
 'tuyos',
 'tuyas',
 'suyo',
 'suya',
 'suyos',
 'suyas',
 'nuestro',
 'nuestra',
 'nuestros',
 'nuestras',
 'vuestro',
 'vuestra',
 'vuestros',
 'vuestras',
 'esos',
 'esas',
 'estoy',
 'estás',
 'está',
 'estamos',
 'estáis',
 'están',
 'esté',
 'estés',
 'estemos',
 'estéis',
 'estén',
 'estaré',
 'estarás',
 'estará',
 'estaremos',
 'estaréis',
 'estarán',
 'estaría',
 'estarías',
 'estaríamos',
 'estaríais',
 'estarían',
 'estaba',
 'estabas',
 'estábamos',
 'estabais',
 'estaban',
 'estuve',
 'estuviste',
 'estuvo',
 'estuvimos',
 'estuvisteis',
 'estuvieron',
 'estuviera',
 'estuvieras',
 'estuviéramos',
 'estuvierais',
 'estuvieran',
 'estuviese',
 'estuvieses',
 'estuviésemos',
 'estuvieseis',
 'estuviesen',
 'estando',
 'estado',
 'estada',
 'estados',
 'estadas',
 'estad',
 'he',
 'has',
 'ha',
 'hemos',
 'habéis',
 'han',
 'haya',
 'hayas',
 'hayamos',
 'hayáis',
 'hayan',
 'habré',
 'habrás',
 'habrá',
 'habremos',
 'habréis',
 'habrán',
 'habría',
 'habrías',
 'habríamos',
 'habríais',
 'habrían',
 'había',
 'habías',
 'habíamos',
 'habíais',
 'habían',
 'hube',
 'hubiste',
 'hubo',
 'hubimos',
 'hubisteis',
 'hubieron',
 'hubiera',
 'hubieras',
 'hubiéramos',
 'hubierais',
 'hubieran',
 'hubiese',
 'hubieses',
 'hubiésemos',
 'hubieseis',
 'hubiesen',
 'habiendo',
 'habido',
 'habida',
 'habidos',
 'habidas',
 'soy',
 'eres',
 'es',
 'somos',
 'sois',
 'son',
 'sea',
 'seas',
 'seamos',
 'seáis',
 'sean',
 'seré',
 'serás',
 'será',
 'seremos',
 'seréis',
 'serán',
 'sería',
 'serías',
 'seríamos',
 'seríais',
 'serían',
 'era',
 'eras',
 'éramos',
 'erais',
 'eran',
 'fui',
 'fuiste',
 'fue',
 'fuimos',
 'fuisteis',
 'fueron',
 'fuera',
 'fueras',
 'fuéramos',
 'fuerais',
 'fueran',
 'fuese',
 'fueses',
 'fuésemos',
 'fueseis',
 'fuesen',
 'sintiendo',
 'sentido',
 'sentida',
 'sentidos',
 'sentidas',
 'siente',
 'sentid',
 'tengo',
 'tienes',
 'tiene',
 'tenemos',
 'tenéis',
 'tienen',
 'tenga',
 'tengas',
 'tengamos',
 'tengáis',
 'tengan',
 'tendré',
 'tendrás',
 'tendrá',
 'tendremos',
 'tendréis',
 'tendrán',
 'tendría',
 'tendrías',
 'tendríamos',
 'tendríais',
 'tendrían',
 'tenía',
 'tenías',
 'teníamos',
 'teníais',
 'tenían',
 'tuve',
 'tuviste',
 'tuvo',
 'tuvimos',
 'tuvisteis',
 'tuvieron',
 'tuviera',
 'tuvieras',
 'tuviéramos',
 'tuvierais',
 'tuvieran',
 'tuviese',
 'tuvieses',
 'tuviésemos',
 'tuvieseis',
 'tuviesen',
 'teniendo',
 'tenido',
 'tenida',
 'tenidos',
 'tenidas',
 'tened']

In [37]:
def remove_stopword1(text):

    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)

    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [38]:
remove_stopword1("This is a simple sentence in which the words are easy to understand and to process.")

'This   simple sentence    words  easy  understand   process.'

In [39]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [40]:
stop_words = stopwords.words('english')

def remove_stopwords(text):
    words = text.split()
    filterwords = []
    for word in words:
        if word.lower() not in stop_words:
            filterwords.append(word)

    return " ".join(filterwords)

In [41]:
df['review'].apply(remove_stopwords)

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production. <br /><br />the f...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy (jake) thi...
4        petter mattei's "love time money" visually stu...
                               ...
49995    thought movie right good job. creative origina...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    catholic taught parochial elementary schools n...
49998    going disagree previous comment side maltin on...
49999    one expects star trek movies high art, fans ex...
Name: review, Length: 50000, dtype: object

## Handling Emojis

In [42]:
import re

def remove_emoji(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map
        "\U0001F1E0-\U0001F1FF"  # flags
        "\U00002700-\U000027BF"  # dingbats
        "\U000024C2-\U0001F251"
        "\U0001F900-\U0001F9FF"  # supplemental symbols
        "\U0001FA70-\U0001FAFF"  # extended symbols
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub('', text)

In [43]:
remove_emoji('Loved the movie. it was 😍😍')

'Loved the movie. it was '

In [44]:
# Convert Emoji to Word

import emoji

print(emoji.demojize('Python is 🔥'))

Python is :fire:

In [45]:
print(emoji.demojize('Loved this movie. it was 😍'))

Loved this movie. it was :smiling_face_with_heart-eyes:

## Tokenization

### 1. Using Split function

In [46]:
sent1 = 'I am going to Pune'
sent1.split()

['I', 'am', 'going', 'to', 'Pune']

In [47]:
sent2 = 'I am Going back to Home. I will stay there for 4 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am Going back to Home',
 ' I will stay there for 4 days',
 " Let's hope the trip to be great"]

In [48]:
# Problem WIth split function
sent3 = 'I am going to pune!'
sent3.split()

['I', 'am', 'going', 'to', 'pune!']

In [49]:
sent4 = 'Where do think i should go? i have 3 days holidays'
sent4.split('.')

['Where do think i should go? i have 3 days holidays']

### 2. Using Regular Expression

In [50]:
import re

sent5 = 'I am going to Pune!'
tokens = re.findall('[\w]+', sent5)
tokens

['I', 'am', 'going', 'to', 'Pune']

In [51]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sentences = re.compile('[.!?]').split(text)
sentences

['Lorem Ipsum is simply dummy text of the printing and typesetting industry',
 "\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book",
 '']

### 3. Using NLTK

In [52]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [53]:
sent6 = 'I am going to visit Home!'
word_tokenize(sent6)

['I', 'am', 'going', 'to', 'visit', 'Home', '!']

In [54]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [55]:
sent7 = 'I Have a Ph.D in A.I'
sent8 = "We're here to help! mail us at hello@gmail.com"
sent9 = 'A 5Km ride cost $10.50'

In [56]:
print(word_tokenize(sent7))
print()
print(word_tokenize(sent8))
print()
print(word_tokenize(sent9))

['I', 'Have', 'a', 'Ph.D', 'in', 'A.I']

['We', "'re", 'here', 'to', 'help', '!', 'mail', 'us', 'at', 'hello', '@', 'gmail.com']

['A', '5Km', 'ride', 'cost', '$', '10.50']

### 4. Using Spacy

In [57]:
import spacy

In [58]:
nlp = spacy.load('en_core_web_sm')

In [59]:
doc1 = nlp(sent7)
doc2 = nlp(sent8)
doc3 = nlp(sent9)

In [60]:
for token in doc3:
    print(token)

A
5Km
ride
cost
$
10.50

## Stemming

In [61]:
from nltk.stem.porter import PorterStemmer

In [62]:
ps = PorterStemmer()

def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [63]:
sample = "Walk Walked Walking Walks"

stem_words(sample)

'walk walk walk walk'

In [64]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more li ke dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more li ke dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [65]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more li ke dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

## Lemmatization

In [3]:
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import string

In [11]:
punctuation = string.punctuation
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."

sentence_words = word_tokenize(sentence)

for word in sentence_words:
    if word in punctuation:
        sentence_words.remove(word)

sentence_words

print("{0:20}{1:20}".format('Word','Lemma'))

for word in sentence_words:
    print("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word, pos = 'v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun